const mongoose = require('mongoose');

const generalsettingSchema = new mongoose.Schema({
  business_type: String,
  com_addr: String,
  com_email: String,
  com_name: String,
  country_code: String,
  email_bcc: String,
  footer_text: String,
  gst_no: String,
  phone: String,
  vat_no: String,
  zipcode: String,
  city: Number,
  company_logo: String,
  country: Number,
  doctype: String,
  docupload_size: String,
  imgtype: String,
  imgupload_size: String,
  state: Number,
  currency: String,
  date_format: String,
  language: String,
  time_format: String,
  imgtype_jpeg: String,
  imgtype_jpg: String,
  imgtype_png: String,
  Default_tax: String,
  auto_round_off: Number,
  currency_set: String,
  decimal_separator: String,
  tax_item: Number,
  thousand_separator: String,
  bank_details: String,
  invoice_client_note: String,
  invoice_number_format: String,
  invoice_predefined_terms: String,
  invoice_prefix: String,
  number_length: String,
  font_size: String,
  pdf_font: String,
  pdf_format: String,
  pdf_logo_url: String,
  pdf_logo_width: String,
  show_pdf_signature_creditnote: Number,
  show_pdf_signature_invoice: Number,
  show_transaction: Number,
  signature_image: String,
  swap_header: String,
  tbl_head_color: String,
  tbl_head_txt_color: String,
  doctype_Doc: String,
  doctype_Docx: String,
  doctype_Pdf: String,
  doctype_Xls: String,
  doctype_Xlsx: String,
  stripe_secret_key: String,
  stripe_publishable_key: String,
});

const Generalsetting = mongoose.model('generalsetting', generalsettingSchema, 'generalsettings');

module.exports = Generalsetting;
